### ISSUE TITLE
Missing requirement(s)

### ISSUE THREAD

**Issue by Javiercerna** [CorentinChauvin/fs_track_builder#1]
https://github.com/CorentinChauvin/fs_track_builder/blob/b3704fa33c3c34c13d1e49f3c4fa18f1c9c0766f/requirements.txt#L1-L2

There are some missing requirements :slightly_smiling_face: 
`pyyaml`

EDIT: It was only that one, I thought there would be more, but not

**Comment by CorentinChauvin** [comment]
Solved in 1bda0bc :slightly_smiling_face:
